export const BEGIN_DIALOGUE = "BEGIN_DIALOGUE";
export const ADVANCE_DIALOGUE_LINE = "ADVANCE_DIALOGUE_LINE";
export const CONTINUE_DIALOGUE = "CONTINUE_DIALOGUE";
export const END_DIALOGUE = "END_DIALOGUE";
