export const ADD_ITEM_TO_INVENTORY = "ADD_ITEM_TO_INVENTORY";
export const REMOVE_ITEM_FROM_INVENTORY = "REMOVE_ITEM_FROM_INVENTORY";
export const MOVE_ITEM_IN_INVENTORY = "MOVE_ITEM_IN_INVENTORY";
export const ASSIGN_HOTKEY_TO_ITEM = "ASSIGN_HOTKEY_TO_ITEM";
export const USE_ITEM = "USE_ITEM";
