export const SET_FOCUSED_SCRIPT = "SET_FOCUSED_SCRIPT";
export const UPDATE_SCRIPT_STATES = "UPDATE_SCRIPT_STATES";

export const LOG_TO_CONSOLE = "LOG_TO_CONSOLE";

export const SAVE_SCRIPT = "SAVE_SCRIPT";
export const LOAD_SCRIPT = "LOAD_SCRIPT";
