export const SET_FOCUSED_SCRIPT = "SET_FOCUSED_SCRIPT";
export const UPDATE_SCRIPT_STATES = "UPDATE_SCRIPT_STATES";

export const LOG_TO_CONSOLE = "LOG_TO_CONSOLE";

export const SET_SCRIPT_LIBRARY_ON_LOAD = "SET_SCRIPT_LIBRARY_ON_LOAD";

export const ADD_SCRIPT_TO_LIBRARY = "ADD_SCRIPT_TO_LIBRARY";
export const REMOVE_SCRIPT_FROM_LIBRARY = "REMOVE_SCRIPT_FROM_LIBRARY";
