export const SET_PLAYER_STATUS = "SET_PLAYER_STATUS";

export const SET_PLAYER_HEALTH = "SET_PLAYER_HEALTH";
export const SET_PLAYER_MANA = "SET_PLAYER_MANA";

export const SET_PLAYER_MAX_HEALTH = "SET_PLAYER_MAX_HEALTH";
export const SET_PLAYER_MAX_MANA = "SET_PLAYER_MAX_MANA";

export const INCREMENT_PLAYER_HEALTH = "INCREMENT_PLAYER_HEALTH";
export const INCREMENT_PLAYER_MANA = "INCREMENT_PLAYER_MANA";
